server:
  port: 8085
  servlet:
    context-path: /eaisp-users-enterprise-api

spring:
  application:
    name: eaisp-users-enterprise-api

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: syam
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect